export const data = [
  {
    taskId: '1',
    name: 'Task Splitter',
    todo: 'test if works editor',
    why: 'to improve what i do and how much i do each task can be split till 2 min task',
    timeCreated: '2023-07-28T17:39:30.708Z',
    lastUpdated: '2023-11-28T17:39:40.387Z',
    timeEnd: '',
    duration: '0',
    overlord: '5',
    repeat: 'never',
    status: 'inactive',
    stage: 'todo',
    type: 'project',
    subtype: 'list',
    size: 'split',
    owner: 'Ubaby',
    priority: '5',
    backupLink: '',
    imageUrl: '',
    imageDataUrl: '',
    tags: 'task splitter',
  },
  {
    taskId: '2',
    name: 'NodeJS Projects',
    todo: 'decide next step',
    why: 'list of useful node',
    timeCreated: '2023-07-28T17:39:30.708Z',
    lastUpdated: '2023-08-16T18:08:23.326Z',
    timeEnd: '',
    duration: '0',
    overlord: '134',
    repeat: 'never',
    status: 'inactive',
    stage: 'todo',
    type: 'js',
    subtype: 'list',
    size: 'split',
    owner: 'Ubaby',
    priority: '0',
    backupLink: '',
    imageUrl: '',
    imageDataUrl: '',
    tags: '',
  },
  {
    taskId: '3',
    name: 'A-Github-Projects',
    todo: 'decide next step',
    why: '',
    timeCreated: '2023-07-28T17:39:30.708Z',
    lastUpdated: '',
    timeEnd: '',
    duration: '0',
    overlord: '134',
    repeat: 'never',
    status: 'inactive',
    stage: 'todo',
    type: '',
    subtype: 'list',
    size: 'split',
    owner: 'Ubaby',
    priority: '0',
    backupLink: '',
    imageUrl: '',
    imageDataUrl: '',
    tags: '',
  },
  {
    taskId: '4',
    name: 'AndroidStudioProjects',
    todo: 'decide next step',
    why: '',
    timeCreated: '2023-07-28T17:39:30.708Z',
    lastUpdated: '2023-09-26T11:24:19.571Z',
    timeEnd: '',
    duration: '0',
    overlord: '134',
    repeat: 'never',
    status: 'inactive',
    stage: 'todo',
    type: '',
    subtype: 'list',
    size: 'split',
    owner: 'Ubaby',
    priority: '1',
    backupLink: '',
    imageUrl: '',
    imageDataUrl: '',
    tags: '',
  },
];
