export const testTemplate = {
  id: 'Rap2DS0nPnXkrNDxRwB7',
  authorId: 'adminId',
  isPublic: false,
  authorName: 'Ubaby',
  tasks: [
    {
      stage: 'todo',
      name: 'multivitamin',
      repeat: 'once',
      tags: '',
      status: 'active',
      owner: '',
      timeEnd: null,
      size: 'do now',
      priority: 0,
      type: 'note',
      duration: 0,
      subtype: 'list',
      imageDataUrl: '',
      backupLink: '',
      timeCreated: {
        seconds: 1695723337,
        nanoseconds: 476000000,
      },
      why: '',
      overlord: 'JR9K3hByeEl7P9Jbls1T',
      taskId: '277',
      lastUpdated: {
        seconds: 1698769391,
        nanoseconds: 864000000,
      },
      todo: '',
      imageUrl: '',
    },
    {
      size: 'do now',
      timeEnd: null,
      subtype: 'list',
      tags: '',
      name: 'white pepper',
      taskId: '262',
      type: 'note',
      lastUpdated: {
        seconds: 1698769377,
        nanoseconds: 743000000,
      },
      imageUrl: '',
      status: 'active',
      overlord: 'JR9K3hByeEl7P9Jbls1T',
      timeCreated: {
        seconds: 1695723337,
        nanoseconds: 474000000,
      },
      todo: '',
      priority: 0,
      imageDataUrl: '',
      owner: '',
      stage: 'todo',
      repeat: 'once',
      why: '',
      duration: 0,
      backupLink: '',
    },
  ],
};
